### PR TITLE
Branch alias, help to keep 1.*@dev in composer.json

### LINKED ISSUE #1: Installing zend-expressive and aura router
Hi, 

This was my composer.json

```
{
    "require": {
        "zendframework/zend-expressive": "1.0.*@rc",
        "aura/router": "^2.3",
        "aura/di": "3.0.*@beta",
        "filp/whoops": "^1.1"
    }
}
```

Later I realised the router was split, so was installing via `composer require zendframework/zend-expressive-aurarouter` and got the error.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for zendframework/zend-expressive-aurarouter ^0.1.1 -> satisfiable by zendframework/zend-expressive-aurarouter[0.1.1].
    - zendframework/zend-expressive-aurarouter 0.1.1 requires zendframework/zend-expressive ^0.5 -> no matching package found.
```

This basically can be resolved with minimum-stability flag, but the problem is expressive installed is 1.0rc1 and the router is looking for 0.5 .

It would have been helpful if there was an alias or 1.x branch so we don't need to require dev-master. Is there any reason a branch as 1.x is not taken for default branch than master ?

Thank you.

### PR DESCRIPTION
**Pull request by harikt**
Trying to fix #1 with `1.*@dev`.

### CODE REVIEW

**Comment by Maks3w** [comment]
Please apply the same format as used here https://github.com/zendframework/zend-expressive-zendviewrenderer/blob/master/composer.json#L14-L18

**Comment by harikt** [comment]
@Maks3w in my understanding 1.x will be the correct way. Else you may want to change the branch alias when the version becomes 1.1, 1.2, 1.3, 1.4 ... . Your thoughts ?

**Comment by Maks3w** [comment]
Branch alias is locked to the feature version same as ZF2 components. I guess `develop` branch will be created after reach the first stable release (1.0.0)

**Comment by harikt** [comment]
This was another way I fixed it https://github.com/harikt/zend-expressive-aurarouter/commit/362e0006c4804a9387469e19109d668e630afdc3#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R18 . Do you think this will be better than the alias then ?

**Comment by Maks3w** [comment]
That is a different thing not related with the branch alias.

**Comment by harikt** [comment]
yes, but that will help to resolve the issue.

_Hari K T_

You can ring me : +91 9388 75 8821

http://harikt.com , https://github.com/harikt ,
http://www.linkedin.com/in/harikt , http://www.xing.com/profile/Hari_KT

Skype  : kthari85
Twitter : harikt

**Comment by Maks3w** [comment]
1. Branch alias is something must do in this repo
2. Expressive didn't be released in stable yet so your new constraint may fail

**Comment by harikt** [comment]
For 1 ) ok, I will make the change
2 ) That is wrong, for it works for me. See https://github.com/harikt/expressive-aura-skelton/blob/master/composer.json . What I did was added minimum-stability flag to rc.

Thank you.

**Pull request closed without merging**
