### PR TITLE
Route wildcard via options

### PR DESCRIPTION
**Pull request by nikolaposa**
This PR provides the ability to set Aura route [`wildcard`](https://github.com/auraphp/Aura.Router/blob/3.x/docs/defining-routes.md#wildcard-attributes) via route options.

### CODE REVIEW

**Comment by harikt** [comment]
@michaelmoussa any reason some of the PR are waiting ?

**Comment by weierophinney** [comment]
@harikt - yes, because some of these require new major versions to support.
(In this case, change to the interface, to add the new argument.)

**Comment by harikt** [comment]
@weierophinney looks like there is no interface changes made.

And also if major versions need to be released why not go for the same ?

**Comment by michaelmoussa** [comment]
@harikt I've only recently begun helping with the project in my spare time and simply have not gotten to this repository yet. I assure you though that every issue and every PR in every Expressive repo will be addressed - it's just going to take some time to catch up.

**Comment by harikt** [comment]
@michaelmoussa sure no problem. I was wondering seeing a 2015 PR waiting to merge not addressed ( ie very sad to see) . ie why pinged you.

Thank you.

**Comment by weierophinney** [comment]
Merged to develop for release with 1.1.0. Thanks, @nikolaposa\!

**Pull request closed without merging**
